### ISSUE TITLE
can't compile on 4.19

### ISSUE THREAD

**Issue by nonchip** [fire/SensibleEditorSourceCodeAccess#20]
cloned to developer plugins folder, added to LinuxEngine.ini, ran `make UE4Editor`:
```While compiling /home/kyra/src/UnrealEngine/Engine/Intermediate/Build/BuildRules/UE4Rules.dll:
ERROR: /home/kyra/src/UnrealEngine/Engine/Plugins/Developer/SublimeTextSourceCodeAccess/Source/SublimeTextSourceCodeAccess/SublimeTextSourceCodeAccess.Build.cs(26,16) : error CS1729: The type `UnrealBuildTool.ModuleRules' does not contain a constructor that takes `0' arguments
ERROR: Unable to compile source files.
```

**Comment by mbc-audiovisuales** [comment]
Edit SublimeTextSourceCodeAccess.Build.cs 

and change line 26:
`public SublimeTextSourceCodeAccess(TargetInfo Target)`
by
`public SublimeTextSourceCodeAccess(ReadOnlyTargetRules Target) : base(Target)`

Worked for me
